### ISSUE TITLE
Instructions on how to apply plugin

### ISSUE THREAD

**Issue by ki82** [kellyrob99/gradle-jslint-plugin#3]
Could you please add some instruction on how to apply the plugin?

I tried with apply plugin 'jslint' and adding the following to buildscript.dependencies, classpath name: 'gradle-jslint-plugin'
When running i get the following error:

> Configuration with name 'jslint' not found.

**Comment by kellyrob99** [comment]
Sorry for the delayed answer, it seems with the latest Gradle(I'm running 1.2 now) the configuration needs to be defined first. Here's a complete setup, assuming you have downloaded the jar file you can update the path appropriately.

``` groovy
apply plugin: 'groovy'
group = 'temp'

repositories.mavenCentral() //needed by the plugin to retrieve the jslint jar

buildscript {
    dependencies {
        classpath fileTree(dir: '/Users/krobinson/Downloads', include: 'gradle-jslint-plugin-0.2-SNAPSHOT.jar')
    }
}
configurations{
    jslint
}
//apply plugin: 'jslint' // doesn't work with the jar presently available, will try to publish an update shortly
apply plugin: org.kar.jslint.gradle.plugin.JSLintPlugin
```

**Comment by kellyrob99** [comment]
Issue has been corrected and usage instructions added to the wiki page. I hope that resolves any problems for you.
